# syntax=docker/dockerfile:experimental

FROM golang:1.19.2-alpine3.16 as dev
RUN apk add --no-cache git make
RUN adduser -D appuser
COPY . /src/
WORKDIR /src

ENV GO111MODULE=on
RUN --mount=type=cache,sharing=locked,id=gomod,target=/go/pkg/mod/cache \
    --mount=type=cache,sharing=locked,id=goroot,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux make build

FROM alpine:3.16.2
# Add Certificates into the image, for anything that does API calls
RUN apk add --no-cache iptables
# Add kube-vip binary
COPY --from=dev /src/kube-vip /
COPY /entrypoint_iptables.sh /
# Adding iptables-wrapper-installer from https://github.com/kubernetes-sigs/iptables-wrappers
ADD https://raw.githubusercontent.com/kubernetes-sigs/iptables-wrappers/v2/iptables-wrapper-installer.sh /
RUN chmod 755 /entrypoint_iptables.sh /iptables-wrapper-installer.sh

ENTRYPOINT ["/entrypoint_iptables.sh"]
