apiVersion: v1
kind: Pod
metadata:
  name: pod-01
  labels:
    env: demo1
spec:
  containers:
    - name: pod-01
      image: thebsdbox/demo:v1
      env:
        - name: CLIENT
          value: "service2"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-02
  labels:
    env: demo2
spec:
  containers:
    - name: pod-02
      image: thebsdbox/demo:v1
      env:
        - name: CLIENT
          value: "service1"
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  clusterIP: None # <= Don't forget!!
  selector:
    env: demo1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  clusterIP: None # <= Don't forget!!
  selector:
    env: demo2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
